name: Deploy to Docker on Ubuntu Server

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build with Maven
        run: mvn clean package -pl app -am

      - name: Build and push Docker image
        run: |
          docker build -t ulvusuleymanov1/edadi-develop:latest .
          docker push ulvusuleymanov1/edadi-develop:latest

      - name: SSH and deploy on Ubuntu server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ulvusuleymanov1/edadi-develop:latest
            docker stop edadi-develop || true
            docker rm edadi-develop || true
            docker run -d --name edadi-develop -p 5000:5000 -p 4000:4000 \
              -e JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:4000" \
              -e CONFIG_SERVER_URL=${{ secrets.CONFIG_SERVER_URL }} \
              ulvusuleymanov1/edadi-develop:latest
          
